micronaut:
  application:
    name: keyManagerGrpc

grpc:
  server:
    port: ${SERVER_PORT:50051}
    keep-alive-time: 1h
    max-inbound-message-size: 1024

datasources:
  default:
    url: jdbc:mysql://localhost:3306/micronaut?useTimezone=true&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    schema-generate: CREATE_DROP
    dialect: MYSQL

jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa.default.properties.hibernate.show_sql: true
jpa.default.properties.hibernate.format_sql: true

jackson:
  serialization:
    writeDateTimestamps: false

itau:
  contas:
    url: "http://localhost:9091"

bcb:
  contas:
    url: 'http://localhost:8082'