micronaut:
  application:
    name: keyManagerGrpc

grpc:
  server:
    port: ${GRPC_SERVER_PORT:50051}

datasources:
  default:
    url: jdbc:mysql://localhost:3306/chavepix?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
    driverClassName: "com.mysql.cj.jdbc.Driver"
    dialect: MYSQL

jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa.default.properties.hibernate.show_sql: true
jpa.default.properties.hibernate.format_sql: true

jackson:
  serialization:
    writeDateTimestamps: false

itau.erp.api.url: http://localhost:9091